const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const assert = require('node:assert/strict');
const path = require('node:path');
const root=path.resolve(__dirname, '..');
let browser;
(async()=> {
 browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1280,height:960},timezoneId:'America/Lima'});
 const page=await context.newPage(); const errors=[], requests=[]; let checks=0;
 const check=(actual, expected, note)=>{assert.deepEqual(actual,expected,note);checks++;};
 page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>errors.push(r.url()));page.on('request',r=>requests.push(r.url()));
 await page.goto(process.env.DEMO_URL || 'http://127.0.0.1:5084'); await page.evaluate(()=>document.fonts.ready);
 check(await page.locator('.venta-card').count(),6,'demo initialized');
 check(await page.locator('#ventas-hoy').textContent(),'S/ 243.50','today total');
 check(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'desktop no horizontal overflow');
 check(requests.every(url=>url.startsWith(process.env.DEMO_URL || 'http://127.0.0.1:5084')),true,'no external resources');
 await page.screenshot({path:path.join(root,'assets/screenshots/screenshot-pos-main.png')});
 await page.locator('[aria-label="Abrir análisis"]').first().click();
 check(await page.locator('#kpi-velocidad').textContent(),'S/ 38.26 / h','weighted demo income/hour');
 await page.screenshot({path:path.join(root,'assets/screenshots/screenshot-pos-analytics.png')});
 await page.keyboard.press('Escape');
 check(await page.locator('#modal-dashboard').evaluate(el=>el.classList.contains('hidden')),true,'dashboard escape');
 await page.locator('#monto').fill('12.34');await page.locator('#vendedor').fill('QA <img src=x onerror="window.xss=1">'); await page.locator('#notas').fill('Prueba <script>window.xss=2</script>');
 await page.locator('#form-venta button[type=submit]').click();
 check(await page.locator('.venta-card').count(),7,'sale added');
 check(await page.locator('#monto').inputValue(),'','successful save resets form');
 check(await page.locator('#ventas-hoy').textContent(),'S/ 255.84','updated total');
 check(await page.evaluate(()=>window.xss),undefined,'no injection executed');
 check(await page.locator('.venta-card img,.venta-card script').count(),0,'markup remains text');
 await page.reload();check(await page.locator('.venta-card').count(),7,'reload persistence');
 await page.locator('[data-action=edit]').first().click();await page.locator('#editar-monto').fill('15.00');await page.locator('#form-editar button[type=submit]').click();
 check(await page.locator('#ventas-hoy').textContent(),'S/ 258.50','edited total');
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('[aria-label="Descargar copia JSON"]').first().click()]);
 const exported=JSON.parse(fs.readFileSync(await download.path(),'utf8'));check(exported.length,7,'backup contains all sales');
 const dialogs=dialog=>dialog.accept();page.on('dialog',dialogs);
 await page.locator('[data-action=delete]').first().click();check(await page.locator('.venta-card').count(),6,'delete');
 await page.locator('[data-filter=semana]').click(); check(await page.locator('[data-filter=semana]').getAttribute('aria-pressed'),'true','filter pressed');
 await page.locator('#import-file').setInputFiles({name:'empty.json',mimeType:'application/json',buffer:Buffer.from('[]')});await page.waitForFunction(()=>document.querySelector('#total-registros').textContent==='0');
 await page.locator('[aria-label="Abrir análisis"]').first().click();check(await page.locator('#kpi-hora-ideal').textContent(),'--:--','empty clears prior KPI');
 check(await page.locator('#kpi-velocidad').textContent(),'S/ 0.00 / h','empty clears revenue/hour');await page.keyboard.press('Escape');
 await page.reload();check(await page.locator('.venta-card').count(),0,'empty storage does not reseed');
 await page.locator('#import-file').setInputFiles({name:'broken.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.waitForFunction(()=>document.querySelector('#toast-mensaje').textContent.includes('JSON válido'));
 check(await page.locator('.venta-card').count(),0,'invalid import preserves data');
 await page.locator('#import-file').setInputFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exported))});await page.waitForFunction(()=>document.querySelector('#total-registros').textContent==='7');
 check(await page.locator('.venta-card').count(),7,'valid backup restored');
 await page.evaluate(()=>{localStorage.setItem('molleventas_db_v1','{invalid');});await page.reload();
 check(await page.locator('#storage-alert').isVisible(),true,'corruption displays recovery');
 check(await page.evaluate(()=>localStorage.getItem('molleventas_db_v1')),'{invalid','corrupt original preserved');
 await page.locator('button', {hasText:'Recargar ejemplo'}).click();await page.waitForFunction(()=>document.querySelector('#total-registros').textContent==='6');
 check(await page.locator('#storage-alert').isVisible(),false,'demo recovery');
 // Simulate quota error: failed durable write must leave both totals and cards untouched.
 await page.evaluate(()=>{window.originalSetItem=Storage.prototype.setItem;Storage.prototype.setItem=()=>{throw new Error('Cuota de almacenamiento alcanzada.');};});
 await page.locator('#monto').fill('10');await page.locator('#form-venta button[type=submit]').click();
 check(await page.locator('.venta-card').count(),6,'failed write leaves cache unchanged');
 check(await page.locator('#monto').inputValue(),'10','failed write preserves form');
 await page.evaluate(()=>{Storage.prototype.setItem=window.originalSetItem;});await page.reload();
 await page.setViewportSize({width:360,height:800});
 check(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'360px no horizontal overflow');
 await page.screenshot({path:path.join(root,'assets/screenshots/screenshot-pos-mobile.png'),fullPage:true});
 await page.locator('[aria-label="Abrir análisis"]').last().click();
 check(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'360px dashboard no horizontal overflow');
 await page.screenshot({path:path.join(root,'assets/screenshots/screenshot-pos-mobile-analytics.png')});
 await page.keyboard.press('Escape');
 await page.setViewportSize({width:1440,height:1080});await page.screenshot({path:path.join(root,'assets/screenshots/upwork-molleventas-4x3.png')});
 check(errors,[],'no browser exceptions or failed requests');
 console.log(JSON.stringify({checks,errors,externalRequests:requests.filter(url=>!url.startsWith(process.env.DEMO_URL || 'http://127.0.0.1:5084')),screenshots:5},null,2));
 await browser.close();
})().catch(error=>{console.error(error);process.exitCode=1;if(browser) browser.close();});
